reddit:
  baseUrl: https://old.reddit.com  # The base URL for accessing the Reddit website.

lemmy:
  baseUrl: https://lemmy.world  # The base URL for accessing the Lemmy website.

communityMap:
  - subreddit: worldnews
    postFilter:
      postLimit: 75  # Limits the number of posts to retrieve from the subreddit.
      minUpvotes: 600      # Sets the minimum number of upvotes a post must have to be included.
      maxDownvotes: 100  # Sets the maximum number of downvotes a post can have to be included.
      minUpvoteRatio: 0.75  # Defines the minimum ratio of upvotes to total votes a post must have to be included.
      maxTimeHours: 20  # Specifies the maximum age (in hours) of a post to be included.
      excludedUrlPatterns: # User defined regular expresions to exclude urls.
        - \.redd\.it$
        - reddit\.com
        - i\.redd.it\/\w+
        - v\.redd.it\/\w+
    community: worldnews@fledd.it
    postIfQuietFor: 0.25 # Posting will be skipped if a post is newer than this amount of hours
    
      

  - subreddit: Positive_News
    postFilter:
      postLimit: 75  # Limits the number of posts to retrieve from the subreddit.
      minUpvotes: 10     # Sets the minimum number of upvotes a post must have to be included.
      maxDownvotes: 3  # Sets the maximum number of downvotes a post can have to be included.
      minUpvoteRatio: 0.75  # Defines the minimum ratio of upvotes to total votes a post must have to be included.
      maxTimeHours: 72  # Specifies the maximum age (in hours) of a post to be included.
      excludedUrlPatterns: # User defined regular expresions to exclude urls.
        - \.redd\.it$
        - reddit\.com
        - i\.redd.it\/\w+
        - v\.redd.it\/\w+
    community: worldnews@fledd.it
    postIfQuietFor: 0.25 # Posting will be skipped if a post is newer than this amount of hours
    
  - subreddit: climate
    postFilter:
      postLimit: 75  # Limits the number of posts to retrieve from the subreddit.
      minUpvotes: 50  # Sets the minimum number of upvotes a post must have to be included.
      maxDownvotes: 10  # Sets the maximum number of downvotes a post can have to be included.
      minUpvoteRatio: 0.75  # Defines the minimum ratio of upvotes to total votes a post must have to be included.
      maxTimeHours: 24  # Specifies the maximum age (in hours) of a post to be included.
      excludedUrlPatterns: # User defined regular expresions to exclude urls.
        - \.redd\.it$
        - reddit\.com
        - i\.redd.it\/\w+
        - v\.redd.it\/\w+
    community: worldnews@fledd.it
    postIfQuietFor: 0.25 # Posting will be skipped if a post is newer than this amount of hours
