reddit:
  baseUrl: https://old.reddit.com

lemmy:
  baseUrl: https://slrpnk.net/

communityMap:
  - subreddit: solarpunk
    postFilter:
      postLimit: 12
      minUpvotes: 10
      maxDownvotes: 1
      minUpvoteRatio: 0.70
      maxTimeHours: 10
    community: solarpunk@slrpnk.net

  
